#!/usr/bin/env python3
"""Token usage of the Claude Code sessions that worked on this repository.

Reads every transcript under ~/.claude/projects whose directory belongs to
this checkout or one of its worktrees (the main tree, `.claude/worktrees/*`,
and sibling checkouts named `msngr-*`), including subagent transcripts, and
prints tokens per day and per model. A streamed reply is written as several
lines sharing one message id; each id is counted once.

    scripts/tokens.py            # markdown tables to stdout
    scripts/tokens.py --write    # also refresh docs/stats/tokens.md
"""
import json
import os
import re
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PROJECTS = Path.home() / ".claude" / "projects"
OUT = REPO / "docs" / "stats" / "tokens.md"

FIELDS = ("input", "cache_create", "cache_read", "output")


def project_dirs():
    stem = "-" + str(REPO).strip("/").replace("/", "-")
    for d in sorted(PROJECTS.iterdir()):
        if d.name == stem or d.name.startswith(stem + "-"):
            yield d


def records():
    for d in project_dirs():
        for path in d.rglob("*.jsonl"):
            with open(path, "rb") as fh:
                for raw in fh:
                    if b'"usage"' not in raw:
                        continue
                    try:
                        rec = json.loads(raw)
                    except ValueError:
                        continue
                    if rec.get("type") != "assistant":
                        continue
                    msg = rec.get("message") or {}
                    usage = msg.get("usage")
                    if not usage:
                        continue
                    yield rec, msg, usage


def collect():
    seen = {}
    for rec, msg, usage in records():
        key = msg.get("id") or rec.get("requestId") or rec.get("uuid")
        ts = rec.get("timestamp")
        if not ts:
            continue
        day = (datetime.fromisoformat(ts.replace("Z", "+00:00"))
               .astimezone().strftime("%Y-%m-%d"))
        model = msg.get("model") or "?"
        vals = (
            usage.get("input_tokens", 0) or 0,
            usage.get("cache_creation_input_tokens", 0) or 0,
            usage.get("cache_read_input_tokens", 0) or 0,
            usage.get("output_tokens", 0) or 0,
        )
        prev = seen.get(key)
        # Lines of one streamed message repeat the usage; keep the largest.
        if prev is None or sum(vals) > sum(prev[2]):
            seen[key] = (day, model, vals)
    by_day = defaultdict(lambda: [0, 0, 0, 0, 0])
    by_model = defaultdict(lambda: [0, 0, 0, 0, 0])
    by_day_model = defaultdict(lambda: defaultdict(int))
    for day, model, vals in seen.values():
        for acc in (by_day[day], by_model[model]):
            for i, v in enumerate(vals):
                acc[i] += v
            acc[4] += 1
        by_day_model[day][model] += sum(vals)
    return by_day, by_model, by_day_model


def fmt(n):
    return f"{n:,}".replace(",", " ")


def table(header, rows):
    out = ["| " + " | ".join(header) + " |",
           "|" + "|".join("---:" if i else "---" for i in range(len(header))) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out)


def render(by_day, by_model, by_day_model):
    total = [0, 0, 0, 0, 0]
    rows = []
    for day in sorted(by_day):
        a = by_day[day]
        for i in range(5):
            total[i] += a[i]
        rows.append([day, fmt(a[0]), fmt(a[1]), fmt(a[2]), fmt(a[3]),
                     fmt(sum(a[:4])), fmt(a[4])])
    rows.append(["**total**", *(f"**{fmt(x)}**" for x in total[:4]),
                 f"**{fmt(sum(total[:4]))}**", f"**{fmt(total[4])}**"])
    days = table(["day", "input", "cache write", "cache read", "output",
                  "all", "replies"], rows)

    mrows = []
    for model, a in sorted(by_model.items(), key=lambda kv: -sum(kv[1][:4])):
        mrows.append([model, fmt(a[0]), fmt(a[1]), fmt(a[2]), fmt(a[3]),
                      fmt(sum(a[:4])), fmt(a[4])])
    models = table(["model", "input", "cache write", "cache read", "output",
                    "all", "replies"], mrows)

    names = [m for m, _ in sorted(by_model.items(),
                                  key=lambda kv: -sum(kv[1][:4]))
             if not m.startswith("<")]
    dm_rows = []
    for day in sorted(by_day_model):
        dm_rows.append([day] + [fmt(by_day_model[day].get(m, 0)) or "0"
                                for m in names])
    day_model = table(["day"] + names, dm_rows)

    now = datetime.now(timezone.utc).astimezone().strftime("%Y-%m-%d %H:%M %Z")
    return f"""# Token usage

Generated by `scripts/tokens.py` on {now}, from the Claude Code transcripts
of every session that worked in this checkout or its worktrees (subagents
included). Days are the host's local calendar. "Cache write" and "cache
read" are the prompt-cache halves of the input; "all" is their sum with
input and output. Streamed replies are counted once per message id.

## Per day

{days}

## Per model

{models}

## Per day and model (all tokens)

{day_model}
"""


def main():
    text = render(*collect())
    if "--write" in sys.argv:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(text)
        print(f"wrote {OUT.relative_to(REPO)}")
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
